== Tuesday 7-22 - Summer / Travel (50m)


=== Ice Breaker (15m) ===

Name tag question

* Favorite color? Why?

What is the Czech word of the day?

Two Truths and a Lie

1. Write down two things that are true about you and one that is not. 
2. Divide into teams of two.
3. From your partner's statements guess which two things are true and which one is false.  


=== Review from Monday (20m) ===

* Any questions?


=== Teach new vocabulary (5-15m) ===

Words to learn:

* trees
* forest
* mountain 
* sand 
* hot 
* humid 
* cold 
* icy 
* crowded 
* isolated 
* busy 
* deserted 
* local 
* foreign 
* urban
* rural

=== Summer Months (10m) ===

Summer 2014 - June 21 to September 21

* June
* July
* August
* September

Birthdays in summer?

Name days in summer?

=== Summer Holidays in the US (20m) ===

[width="70%",options="header",cols="3,2,5"]
|=======
| Day of week | Date   | Holiday
| Saturday    | Jun 21 | June Solstice
| Friday      | Jul 4  | Independence Day
| Monday      | Sep 1  | Labor Day
| Sunday      | Sep 7  | National Grandparents Day
| Tuesday     | Sep 23 | September equinox
|=======

=== Location Game (30m) ===

Descriptions of following places print 3 sets of cards 

1. Rainforest/ jungle, desert, Disneyland, Arctic Tundra, Prague, Beach, Village, forest
2. Divide groups into three teams or play flyswatter style.
3. Use the above vocabulary words to describe a certain card allow the teams to use process of elimination to find the one card that ultimately matches.

*****************
* SEGUE: Ask where have you travelled, how do you get there?
*****************

=== Modes of Transportation (45m) ===

Depending on their level hand out modes of transportation match up sheet or verbs about transportation.

American Currency

Intro Game divide into partners, give fake money, tell them to make x amount compare totals.

Basic coin worksheet 

Review 

I am going on a trip and I need ABC’s or Green Glass Door


