== Thursday 7-24 - Winter (50m)

Name tag question: Favorite time of the year?

What is the Czech word of the day?

=== Review from Wednesday (20m) ===

* Any questions?

=== Czech word of the day ===

What is today's word?

=== Winter Months (10m) ===

Winter dates - December 21 to March 20

* December
* January
* February
* March

=== Winter Holidays in the US (20m) ===

[width="70%",options="header",cols="3,2,5"]
|=======
| Day of week | Date   | Holiday
| Sunday      | Dec 21 | December Solstice
| Wednesday   | Dec 24 | Christmas Eve
| Thursday    | Dec 25 | Christmas Day
| Wednesday   | Dec 31 | New Year's Eve
| Thursday    | Jan 1  | New Year's Day
| Monday      | Feb 2  | Groundhog Day
| Saturday    | Feb 14 | Valentine's Day
| Sunday      | Mar 8  | Daylight Saving Time starts "spring forward"
| Tuesday     | Mar 17 | St. Patrick's Day
| Thursday    | Mar 20 | March equinox
|=======

=== Intro Game ===
Sheet game / name games

Descriptive words

* Salty 
* chocolate 
* creamy 
* sweet 
* spicy 
* tough chewy 
* hot 
* minty 
* cool 
* refreshing 
* fruity

Sample foods:

*	Ding Dongs
*	Goldfish/ pretzels
*	Jerky
*	Cinnamon bears
*	Gum
*	Laffy Taffy

Order off Menus: 

What words do we recognize? Descriptive words from previously. 

Practice ordering:

* Phrases like: May I have [underline]#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#?
* Does this have [underline]#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#?
* Are the tacos too [underline]#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#?
* I would like a cheeseburger without [underline]#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#.

=== Explain Thanksgiving ===

Thanksgiving is a very American holiday. It is celebrated on the fourth Thursday in November every year. It used to be a religious holiday to give thanks to God for the early settlers, or Pilgrims, arriving in America safely. Thanksgiving is also meant to give thanks to Native Americans for teaching the pilgrims how to catch eels and grow corn in Plymouth, Massachusetts. 

In 1941, President Roosevelt made Thanksgiving a federal holiday.

The main event of any Thanksgiving is the Thanksgiving dinner. It is traditional to have baked or roasted turkey. This is usually accompanied with mashed potatoes, sweet potatoes, fall vegetables, cranberry sauce, and gravy. Pumpkin pie is the most commonly eaten dessert. 

The Thanksgiving holiday weekend is one of the busiest times of the year for traveling. It is a four-day or five-day weekend vacation for most schools and colleges, and many businesses and government workers get three or four days off. 

Thanksgiving is also the unofficial signal for Christmas preparations to begin. Once Thanksgiving finishes, stores fill their shelves with Christmas goods.

Hold up and explain each Traditional Food with corresponding picture: 

* mashed potatoes
* green bean casserole
* stuffing
* cranberry sauce
* turkey
* sweet potatoes


Take turns saying what we are thankful for

Mock thanksgiving

*	What everyone is thankful for?
*	Pass food
*	Comment on food

=== Idioms - Work (30m) ===

[options="header",cols="2,3"]
|=======
| Term                            | Meaning
| Bite off more than one can chew | To take on more responsibility than one can manage.
| Burn the midnight oil           | To work late into the night, alluding to the time before electric lighting.
| By the seat of one's pants      | To achieve through instinct or do something without advance preparation.
| By the skin of one's teeth      | Narrowly; barely. Usually used in regard to a narrow escape from a disaster.
| Call it a day                   | To declare the end of a task.
| Cut the mustard                 | To perform well; to meet expectations.
| In the black                    | To be making money.
| In the red                      | To be losing money.
| Living hand to mouth            | To be poor, to have difficulty supporting yourself.
| On the ball                     | To be paying attention, to respond promptly, to be doing one's job.
| Piece of cake                   | A job, task or other activity that is pleasant – or, by extension, easy or simple.
|=======

=== Review ===

Grocery Game

