== Monday 7-21 - Spring?

4 hours of content

More introductions

Idioms

=== Spring Months ===

Spring 2014 - March 20 to June 20

* March
* April
* May
* June

Birthdays in spring?

Name days in spring?

=== Spring Holidays ===


* Easter
* May day
* St Patrick's Day

=== Verbing ===

Making a noun into a verb. If we are eating lunch, we are "lunching".

=== Guess Who ===

What are the rules here?

=== Would You Rather ===

1. Would you rather take an ice cold shower and be clean or not shower at all?
2. Would you rather be able to eat anything and any quantity of food with no negative health effects, or be refreshed and well rested after only three hours of sleep?
3. Would you rather drink a bowl full of gravy or have a large spider caught in your hair?
4. Would you rather receive a life time supply of meals from your favorite restaurant or a life time supply of gasoline?
5. Would you rather meet an alien visitor or travel to outer space? Superman?
6. Listen only to bagpipe music or only to banjo music?
7. Wear an eye patch or have a peg leg?
8. Be a cat or be a dog?
9. Have comically large feet or a comically oversized head?
10. Have knee length hair or have a one foot tall Mohawk?


